name: 🆕Feature Request
description: Suggest an idea for this project
body:
    - type: textarea
      id: description
      attributes:
          label: Is your feature request related to a problem? Please describe.
          placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      validation:
          required: true
    - type: textarea
      id: solution
      attributes:
          label: Describe the solution you'd like
          placeholder: A clear and concise description of what you want to happen.
      validation:
          required: true
    - type: textarea
      id: alternatives
      attributes:
          label: Describe alternatives you've considered
          placeholder: A clear and concise description of any alternative solutions or features you've considered.
      validation:
          required: true
    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          placeholder: Add any other context or screenshots about the feature request here. Highlight this area and drag and drop any files to attach them
